# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_likelihood_hier <- function(mu_f, mu_m, d, len, indexes, male_map, female_map, prob, intercept = 0.0) {
    .Call(`_RohMut_cpp_likelihood_hier`, mu_f, mu_m, d, len, indexes, male_map, female_map, prob, intercept)
}

cpp_likelihood_hier_boundary <- function(mu_f, mu_m, d, len, indexes, male_map, female_map, male_start, female_start, male_end, female_end, prob, intercept = 0.0) {
    .Call(`_RohMut_cpp_likelihood_hier_boundary`, mu_f, mu_m, d, len, indexes, male_map, female_map, male_start, female_start, male_end, female_end, prob, intercept)
}

#' Estimate the mutation rate using EM
#'
#' @param mu1 Starting value for the female's mutation parameter
#' @param mu2 Starting value for the male's mutation parameter
#' @param mutation Vector of the number of mutations in a segment
#' @param len Vector of the length of a segment
#' @param indexes List of vector, where each vector is the indexes of the segments for an individual
#' @param maxiter Maximum number of EM iterations
#' @param eps The algorithm stops when the parameters change is less than eps, |prev_mu - mu| < eps
#' @param prob Matrix of probabilities, where the first column is the probability of being first cousin, and the second of second cousin.
#' @param estimate_intercept Whether to estimate the intercept as well, intercept is used when there's genotyping error.
#' @param intercept Starting value for the intercept.
#' @param stochastic If true, an incremental version is used instead.
#' @return An estimate of the male mutation rate, female mutation rate and of the intercept.
cpp_em_map <- function(mu1, mu2, mutation, len, indexes, maxiter, eps, prob, male_map, female_map, male_start = NA_real_, female_start = NA_real_, male_end = NA_real_, female_end = NA_real_, stochastic = FALSE, estimate_intercept = FALSE, intercept = 0.0) {
    .Call(`_RohMut_cpp_em_map`, mu1, mu2, mutation, len, indexes, maxiter, eps, prob, male_map, female_map, male_start, female_start, male_end, female_end, stochastic, estimate_intercept, intercept)
}

#' Estimate the mutation rate using EM
#'
#' @param mu1 Starting value for the female's mutation parameter
#' @param mu2 Starting value for the male's mutation parameter
#' @param mutation Vector of the number of mutations in a segment
#' @param len Vector of the length of a segment
#' @param indexes List of vector, where each vector is the indexes of the segments for an individual
#' @param maxiter Maximum number of EM iterations
#' @param eps The algorithm stops when the parameters change is less than eps, |prev_mu - mu| < eps
#' @param prob Matrix of probabilities, where the first column is the probability of being first cousin, and the second of second cousin.
#' @param estimate_intercept Whether to estimate the intercept as well, intercept is used when there's genotyping error.
#' @param intercept Starting value for the intercept.
#' @param stochastic If true, an incremental version is used instead.
#' @return An estimate of the male mutation rate, female mutation rate and of the intercept.
cpp_em <- function(mu1, mu2, mutation, len, indexes, maxiter, eps, prob, stochastic = FALSE, estimate_intercept = FALSE, intercept = 0.0) {
    .Call(`_RohMut_cpp_em`, mu1, mu2, mutation, len, indexes, maxiter, eps, prob, stochastic, estimate_intercept, intercept)
}

